sudo: required
dist: trusty
language: ruby

before_install:
- gem install asciidoctor -v 1.5.2
- gem install tilt
- sudo pip install git+https://github.com/gitenberg-dev/gitberg
- sudo pip install git+https://github.com/gitenberg-dev/pg-epubmaker
script:
- VERSION=`ruby -e "require 'yaml'; meta = YAML.load_file('metadata.yaml'); puts meta['_version'];"`
- git clone https://github.com/gitenberg-dev/asciidoctor-htmlbook.git
- sudo pip install -r asciidoctor-htmlbook/gitberg-machine/requirements.txt

- /usr/bin/python -c "from gitenberg import travis; travis.build_epub()"
- ebook-convert book.epub book.mobi
- xvfb-run ebook-convert book.epub book.pdf
notifications:
  webhooks:
    urls:
      - https://unglue.it/api/travisci/webhook
    on_success: always
    on_failure: never
    on_start: never
deploy:
  skip_cleanup: true
  provider: releases
  api_key:
    secure: IXsrgaMfho/8yRHaDzRZoidhTJQn7HLbuuBtpTX+B9AjhzXrOzr6qZvtgcVYyKAUVeAfAnApYDqt+kPNbG+m6IF2usOq8Rg/liyvyVqYdsoiqGFCMbiSqNI9Qq3PVLW2yWGDqpujmsKJGRHeMZGRhWK9j3kBnQ04lo8jzy1TBz0t2FGCEQ1Ag4ZPkWD2dUIuJ8X8Y/g+ffcPgfxrhefPGC0Q4L4hOprE5tvkxxctDRbbn/bhxynPSYkj2+RUvMcUGD2Ng/aK++kPwn4lrqYpxRmuhJYdyZyHqTDOmxLasPnpTEcgd4qfI533zrC/u6Ke36svVY4ybYU+ap4MRfgyqETaldOsrmlM1TxMDoX63ERUYq5Ujffvyaps6EpaY11Cp/X8nDgrbhOy4OxnJBcDvFasdrMsbM2lWkVAg7JK6ybOgnFnDKpiAX1QOAqSKIgt5Rt66uz67Z9rT+1q48TGeMMEuVNtVyiDeOV2HdNHjVvKVOQgwj0UZAI15zCZkziz6+QZ16HSpNM8s/6FOjnh4cyJ/qtXcrmP0OH/U/leXixen02s8bs1lU4OxQA2ZFww5VA758/MOJrwcWxmfaAc+WIuR5L7nCoNRu1Gl4zpfm7G8SPZ81aonBwauanCukHO40vEO5Mj7knP5MgWeJakV/IGwUInoqT7l/NBs6CAbMY=
  file:
    - book.epub
    - book.mobi
    - book.pdf
  on:
    repo: GITenberg/The-Foundations--An-Extravagant-Play-_2916
    tags: true
addons:
  apt:
    packages:
    - xsltproc
    - xvfb
    - calibre
    - python-pip
    - git
    - python-dev
    - libjpeg-dev
    - libpng-dev
    - libfreetype6
    - libfreetype6-dev
    - zlib1g-dev
    - python-lxml
    - libxml2-dev
    - libxslt1-dev
    - tidy